/********************************************************************
版权(C),烟台创为新能源科技有限公司
文件名：GpioMap.c
作者: JWH
版本号:1.0
生成日期:2025.9.24
概述:   针对使用GD32F307芯片的引脚进行封装并命名:
        支持 LQFP144 (GD32F307Zx), LQFP100 (GD32F307Vx),
        和 LQFP64 (GD32F307Rx) 封装。
        在其他测试文件内所引用的引脚均使用本文件的引脚封装名。
修改日志：
    - 2025.9.24: Added pin mapping for GD32F307Vx (LQFP100)
                 and restructured with #if defined for easier selection.
*********************************************************************/

#include "GpioMap.h"

/*
 * Select the target device by uncommenting one of the following lines
 * in your project's configuration file or header.
 */
// #define USE_GD32F307_ZX // For LQFP144 package
// #define USE_GD32F307_VX // For LQFP100 package
// #define USE_GD32F307_RX // For LQFP64 package

#if defined(USE_GD32F307_ZX)
/********************************************************************
 * Pin mapping for GD32F307Zx (LQFP144)
 ********************************************************************/
const STR_GPIO_MAP GD32ZxGpioList[GD32F307Zx + 1] =
{
    [1]   = { GPIOE, GPIO_PIN_2   },
    [2]   = { GPIOE, GPIO_PIN_3   },
    [3]   = { GPIOE, GPIO_PIN_4   },
    [4]   = { GPIOE, GPIO_PIN_5   },
    [5]   = { GPIOE, GPIO_PIN_6   },
    [7]   = { GPIOC, GPIO_PIN_13  },
    [8]   = { GPIOC, GPIO_PIN_14  },
    [9]   = { GPIOC, GPIO_PIN_15  },
    [10]  = { GPIOF, GPIO_PIN_0   },
    [11]  = { GPIOF, GPIO_PIN_1   },
    [12]  = { GPIOF, GPIO_PIN_2   },
    [13]  = { GPIOF, GPIO_PIN_3   },
    [14]  = { GPIOF, GPIO_PIN_4   },
    [15]  = { GPIOF, GPIO_PIN_5   },
    [18]  = { GPIOF, GPIO_PIN_6   },
    [19]  = { GPIOF, GPIO_PIN_7   },
    [20]  = { GPIOF, GPIO_PIN_8   },
    [21]  = { GPIOF, GPIO_PIN_9   },
    [22]  = { GPIOF, GPIO_PIN_10  },
    [26]  = { GPIOC, GPIO_PIN_0   },
    [27]  = { GPIOC, GPIO_PIN_1   },
    [28]  = { GPIOC, GPIO_PIN_2   },
    [29]  = { GPIOC, GPIO_PIN_3   },
    [34]  = { GPIOA, GPIO_PIN_0   },
    [35]  = { GPIOA, GPIO_PIN_1   },
    [36]  = { GPIOA, GPIO_PIN_2   },
    [37]  = { GPIOA, GPIO_PIN_3   },
    [40]  = { GPIOA, GPIO_PIN_4   },
    [41]  = { GPIOA, GPIO_PIN_5   },
    [42]  = { GPIOA, GPIO_PIN_6   },
    [43]  = { GPIOA, GPIO_PIN_7   },
    [44]  = { GPIOC, GPIO_PIN_4   },
    [45]  = { GPIOC, GPIO_PIN_5   },
    [46]  = { GPIOB, GPIO_PIN_0   },
    [47]  = { GPIOB, GPIO_PIN_1   },
    [48]  = { GPIOB, GPIO_PIN_2   },
    [49]  = { GPIOF, GPIO_PIN_11  },
    [50]  = { GPIOF, GPIO_PIN_12  },
    [53]  = { GPIOF, GPIO_PIN_13  },
    [54]  = { GPIOF, GPIO_PIN_14  },
    [55]  = { GPIOF, GPIO_PIN_15  },
    [56]  = { GPIOG, GPIO_PIN_0   },
    [57]  = { GPIOG, GPIO_PIN_1   },
    [58]  = { GPIOE, GPIO_PIN_7   },
    [59]  = { GPIOE, GPIO_PIN_8   },
    [60]  = { GPIOE, GPIO_PIN_9   },
    [63]  = { GPIOE, GPIO_PIN_10  },
    [64]  = { GPIOE, GPIO_PIN_11  },
    [65]  = { GPIOE, GPIO_PIN_12  },
    [66]  = { GPIOE, GPIO_PIN_13  },
    [67]  = { GPIOE, GPIO_PIN_14  },
    [68]  = { GPIOE, GPIO_PIN_15  },
    [69]  = { GPIOB, GPIO_PIN_10  },
    [70]  = { GPIOB, GPIO_PIN_11  },
    [73]  = { GPIOB, GPIO_PIN_12  },
    [74]  = { GPIOB, GPIO_PIN_13  },
    [75]  = { GPIOB, GPIO_PIN_14  },
    [76]  = { GPIOB, GPIO_PIN_15  },
    [77]  = { GPIOD, GPIO_PIN_8   },
    [78]  = { GPIOD, GPIO_PIN_9   },
    [79]  = { GPIOD, GPIO_PIN_10  },
    [80]  = { GPIOD, GPIO_PIN_11  },
    [81]  = { GPIOD, GPIO_PIN_12  },
    [82]  = { GPIOD, GPIO_PIN_13  },
    [85]  = { GPIOD, GPIO_PIN_14  },
    [86]  = { GPIOD, GPIO_PIN_15  },
    [87]  = { GPIOG, GPIO_PIN_2   },
    [88]  = { GPIOG, GPIO_PIN_3   },
    [89]  = { GPIOG, GPIO_PIN_4   },
    [90]  = { GPIOG, GPIO_PIN_5   },
    [91]  = { GPIOG, GPIO_PIN_6   },
    [92]  = { GPIOG, GPIO_PIN_7   },
    [93]  = { GPIOG, GPIO_PIN_8   },
    [96]  = { GPIOC, GPIO_PIN_6   },
    [97]  = { GPIOC, GPIO_PIN_7   },
    [98]  = { GPIOC, GPIO_PIN_8   },
    [99]  = { GPIOC, GPIO_PIN_9   },
    [100] = { GPIOA, GPIO_PIN_8   },
    [101] = { GPIOA, GPIO_PIN_9   },
    [102] = { GPIOA, GPIO_PIN_10  },
    [103] = { GPIOA, GPIO_PIN_11  },
    [104] = { GPIOA, GPIO_PIN_12  },
    [105] = { GPIOA, GPIO_PIN_13  },
    [109] = { GPIOA, GPIO_PIN_14  },
    [110] = { GPIOA, GPIO_PIN_15  },
    [111] = { GPIOC, GPIO_PIN_10  },
    [112] = { GPIOC, GPIO_PIN_11  },
    [113] = { GPIOC, GPIO_PIN_12  },
    [114] = { GPIOD, GPIO_PIN_0   },
    [115] = { GPIOD, GPIO_PIN_1   },
    [116] = { GPIOD, GPIO_PIN_2   },
    [117] = { GPIOD, GPIO_PIN_3   },
    [118] = { GPIOD, GPIO_PIN_4   },
    [119] = { GPIOD, GPIO_PIN_5   },
    [122] = { GPIOD, GPIO_PIN_6   },
    [123] = { GPIOD, GPIO_PIN_7   },
    [124] = { GPIOG, GPIO_PIN_9   },
    [125] = { GPIOG, GPIO_PIN_10  },
    [126] = { GPIOG, GPIO_PIN_11  },
    [127] = { GPIOG, GPIO_PIN_12  },
    [128] = { GPIOG, GPIO_PIN_13  },
    [129] = { GPIOG, GPIO_PIN_14  },
    [132] = { GPIOG, GPIO_PIN_15  },
    [133] = { GPIOB, GPIO_PIN_3   },
    [134] = { GPIOB, GPIO_PIN_4   },
    [135] = { GPIOB, GPIO_PIN_5   },
    [136] = { GPIOB, GPIO_PIN_6   },
    [137] = { GPIOB, GPIO_PIN_7   },
    [139] = { GPIOB, GPIO_PIN_8   },
    [140] = { GPIOB, GPIO_PIN_9   },
    [141] = { GPIOE, GPIO_PIN_0   },
    [142] = { GPIOE, GPIO_PIN_1   },
};
const STR_GPIO_MAP *g_gpio_ptr = GD32ZxGpioList;
const int g_gpio_count = sizeof(GD32ZxGpioList) / sizeof(GD32ZxGpioList[0]);

#elif defined(USE_GD32F307_VX)
/********************************************************************
 * Pin mapping for GD32F307Vx (LQFP100) - NEWLY ADDED
 ********************************************************************/
const STR_GPIO_MAP GD32VxGpioList[GD32F307Vx + 1] =
{
    [1]   = { GPIOE, GPIO_PIN_2  },
    [2]   = { GPIOE, GPIO_PIN_3  },
    [3]   = { GPIOE, GPIO_PIN_4  },
    [4]   = { GPIOE, GPIO_PIN_5  },
    [5]   = { GPIOE, GPIO_PIN_6  },
    [7]   = { GPIOC, GPIO_PIN_13 },
    [8]   = { GPIOC, GPIO_PIN_14 },
    [9]   = { GPIOC, GPIO_PIN_15 },
    [15]  = { GPIOC, GPIO_PIN_0  },
    [16]  = { GPIOC, GPIO_PIN_1  },
    [17]  = { GPIOC, GPIO_PIN_2  },
    [18]  = { GPIOC, GPIO_PIN_3  },
    [23]  = { GPIOA, GPIO_PIN_0  },
    [24]  = { GPIOA, GPIO_PIN_1  },
    [25]  = { GPIOA, GPIO_PIN_2  },
    [26]  = { GPIOA, GPIO_PIN_3  },
    [29]  = { GPIOA, GPIO_PIN_4  },
    [30]  = { GPIOA, GPIO_PIN_5  },
    [31]  = { GPIOA, GPIO_PIN_6  },
    [32]  = { GPIOA, GPIO_PIN_7  },
    [33]  = { GPIOC, GPIO_PIN_4  },
    [34]  = { GPIOC, GPIO_PIN_5  },
    [35]  = { GPIOB, GPIO_PIN_0  },
    [36]  = { GPIOB, GPIO_PIN_1  },
    [37]  = { GPIOB, GPIO_PIN_2  },
    [38]  = { GPIOE, GPIO_PIN_7  },
    [39]  = { GPIOE, GPIO_PIN_8  },
    [40]  = { GPIOE, GPIO_PIN_9  },
    [41]  = { GPIOE, GPIO_PIN_10 },
    [42]  = { GPIOE, GPIO_PIN_11 },
    [43]  = { GPIOE, GPIO_PIN_12 },
    [44]  = { GPIOE, GPIO_PIN_13 },
    [45]  = { GPIOE, GPIO_PIN_14 },
    [46]  = { GPIOE, GPIO_PIN_15 },
    [47]  = { GPIOB, GPIO_PIN_10 },
    [48]  = { GPIOB, GPIO_PIN_11 },
    [51]  = { GPIOB, GPIO_PIN_12 },
    [52]  = { GPIOB, GPIO_PIN_13 },
    [53]  = { GPIOB, GPIO_PIN_14 },
    [54]  = { GPIOB, GPIO_PIN_15 },
    [55]  = { GPIOD, GPIO_PIN_8  },
    [56]  = { GPIOD, GPIO_PIN_9  },
    [57]  = { GPIOD, GPIO_PIN_10 },
    [58]  = { GPIOD, GPIO_PIN_11 },
    [59]  = { GPIOD, GPIO_PIN_12 },
    [60]  = { GPIOD, GPIO_PIN_13 },
    [61]  = { GPIOD, GPIO_PIN_14 },
    [62]  = { GPIOD, GPIO_PIN_15 },
    [63]  = { GPIOC, GPIO_PIN_6  },
    [64]  = { GPIOC, GPIO_PIN_7  },
    [65]  = { GPIOC, GPIO_PIN_8  },
    [66]  = { GPIOC, GPIO_PIN_9  },
    [67]  = { GPIOA, GPIO_PIN_8  },
    [68]  = { GPIOA, GPIO_PIN_9  },
    [69]  = { GPIOA, GPIO_PIN_10 },
    [70]  = { GPIOA, GPIO_PIN_11 },
    [71]  = { GPIOA, GPIO_PIN_12 },
    [72]  = { GPIOA, GPIO_PIN_13 },
    [76]  = { GPIOA, GPIO_PIN_14 },
    [77]  = { GPIOA, GPIO_PIN_15 },
    [78]  = { GPIOC, GPIO_PIN_10 },
    [79]  = { GPIOC, GPIO_PIN_11 },
    [80]  = { GPIOC, GPIO_PIN_12 },
    [81]  = { GPIOD, GPIO_PIN_0  },
    [82]  = { GPIOD, GPIO_PIN_1  },
    [83]  = { GPIOD, GPIO_PIN_2  },
    [84]  = { GPIOD, GPIO_PIN_3  },
    [85]  = { GPIOD, GPIO_PIN_4  },
    [86]  = { GPIOD, GPIO_PIN_5  },
    [87]  = { GPIOD, GPIO_PIN_6  },
    [88]  = { GPIOD, GPIO_PIN_7  },
    [89]  = { GPIOB, GPIO_PIN_3  },
    [90]  = { GPIOB, GPIO_PIN_4  },
    [91]  = { GPIOB, GPIO_PIN_5  },
    [92]  = { GPIOB, GPIO_PIN_6  },
    [93]  = { GPIOB, GPIO_PIN_7  },
    [95]  = { GPIOB, GPIO_PIN_8  },
    [96]  = { GPIOB, GPIO_PIN_9  },
    [97]  = { GPIOE, GPIO_PIN_0  },
    [98]  = { GPIOE, GPIO_PIN_1  },
};
const STR_GPIO_MAP *g_gpio_ptr = GD32VxGpioList;
const int g_gpio_count = sizeof(GD32VxGpioList) / sizeof(GD32VxGpioList[0]);

#elif defined(USE_GD32F307_RX)
/********************************************************************
 * Pin mapping for GD32F307Rx (LQFP64)
 ********************************************************************/
const STR_GPIO_MAP GD32RxGpioList[GD32F307Rx + 1] =
{
    [2]  = { GPIOC, GPIO_PIN_13 },
    [3]  = { GPIOC, GPIO_PIN_14 },
    [4]  = { GPIOC, GPIO_PIN_15 },
    [8]  = { GPIOC, GPIO_PIN_0  },
    [9]  = { GPIOC, GPIO_PIN_1  },
    [10] = { GPIOC, GPIO_PIN_2  },
    [11] = { GPIOC, GPIO_PIN_3  },
    [14] = { GPIOA, GPIO_PIN_0  },
    [15] = { GPIOA, GPIO_PIN_1  },
    [16] = { GPIOA, GPIO_PIN_2  },
    [17] = { GPIOA, GPIO_PIN_3  },
    [20] = { GPIOA, GPIO_PIN_4  },
    [21] = { GPIOA, GPIO_PIN_5  },
    [22] = { GPIOA, GPIO_PIN_6  },
    [23] = { GPIOA, GPIO_PIN_7  },
    [24] = { GPIOC, GPIO_PIN_4  },
    [25] = { GPIOC, GPIO_PIN_5  },
    [26] = { GPIOB, GPIO_PIN_0  },
    [27] = { GPIOB, GPIO_PIN_1  },
    [28] = { GPIOB, GPIO_PIN_2  },
    [29] = { GPIOB, GPIO_PIN_10 },
    [30] = { GPIOB, GPIO_PIN_11 },
    [33] = { GPIOB, GPIO_PIN_12 },
    [34] = { GPIOB, GPIO_PIN_13 },
    [35] = { GPIOB, GPIO_PIN_14 },
    [36] = { GPIOB, GPIO_PIN_15 },
    [37] = { GPIOC, GPIO_PIN_6  },
    [38] = { GPIOC, GPIO_PIN_7  },
    [39] = { GPIOC, GPIO_PIN_8  },
    [40] = { GPIOC, GPIO_PIN_9  },
    [41] = { GPIOA, GPIO_PIN_8  },
    [42] = { GPIOA, GPIO_PIN_9  },
    [43] = { GPIOA, GPIO_PIN_10 },
    [44] = { GPIOA, GPIO_PIN_11 },
    [45] = { GPIOA, GPIO_PIN_12 },
    [46] = { GPIOA, GPIO_PIN_13 },
    [49] = { GPIOA, GPIO_PIN_14 },
    [50] = { GPIOA, GPIO_PIN_15 },
    [51] = { GPIOC, GPIO_PIN_10 },
    [52] = { GPIOC, GPIO_PIN_11 },
    [53] = { GPIOC, GPIO_PIN_12 },
    [54] = { GPIOD, GPIO_PIN_2  },
    [55] = { GPIOB, GPIO_PIN_3  },
    [56] = { GPIOB, GPIO_PIN_4  },
    [57] = { GPIOB, GPIO_PIN_5  },
    [58] = { GPIOB, GPIO_PIN_6  },
    [59] = { GPIOB, GPIO_PIN_7  },
    [61] = { GPIOB, GPIO_PIN_8  },
    [62] = { GPIOB, GPIO_PIN_9  },
};
const STR_GPIO_MAP *g_gpio_ptr = GD32RxGpioList;
const int g_gpio_count = sizeof(GD32RxGpioList) / sizeof(GD32RxGpioList[0]);

#else
	#error
#endif
